package ch.unige.pinfo1;

public enum Tags {
    ALCOOL, ALLEMAND, ANGLAIS, ANIMAUX, ARCHEOLOGIE, ARTS_MARTIAUX, BATTELLE, BIOLOGIE, CHIMIE, CINEMA, CLIMAT, CMU, COMPETITION,
    DATCHA, DESSIN, DROIT, ECONOMIE, ESPAGNOL, ESPORT, ETUDES, ETUDIANTS, FESTIVALS, FOOTBALL, FRANCAIS, HANDICAPE, HISTOIRE,
    HOCKEY, INFORMATIQUE, ITALIEN, JEUX_VIDEO, LANGUES_ETRANGERES, LETTRES, MALE_ALPHA, MATHEMATIQUES, MEDECINE, MONTAGNE, 
    MUSIQUE, NATURE, NOURRITURE, PHILOSOPHIE, PHYSIQUE, PLAGE, PORTUGAIS, PSYCHOLOGIE, RESEAUX_SOCIAUX, SERIES, SOLITAIRE, 
    SORTIE, SPORTS, TATOUAGE, UNI_BASTION, UNI_DUFOUR, UNI_MAIL, UNI_SCIENCES, VOITURES, VOYAGE
}
